//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Gestion_Electrica
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioFijoComercialización
    {
        public int Id { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<decimal> De0a25kWh { get; set; }
        public Nullable<decimal> De26a50kWh { get; set; }
        public Nullable<decimal> De51a100kWh { get; set; }
        public Nullable<decimal> De101a150kWh { get; set; }
        public Nullable<decimal> De151a500kWh { get; set; }
        public Nullable<decimal> De501a1000kWh { get; set; }
        public Nullable<decimal> Mayorde1000kWh { get; set; }
        public string Compañia { get; set; }
    }
}
