//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Gestion_Electrica
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioKwhPorMes
    {
        public int Id { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<decimal> Primeros25kWh { get; set; }
        public Nullable<decimal> Siguientes25kWh { get; set; }
        public Nullable<decimal> Siguientes50kWh1 { get; set; }
        public Nullable<decimal> Siguientes50kWh2 { get; set; }
        public Nullable<decimal> Siguientes350kWh { get; set; }
        public Nullable<decimal> Siguientes500kWh { get; set; }
        public Nullable<decimal> Adicionalesa1000kWh { get; set; }
        public string Compañia { get; set; }
    }
}
