//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Gestion_Electrica
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GISELEntities : DbContext
    {
        public GISELEntities()
            : base("name=GISELEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<agregarServicioEléctrico> agregarServicioEléctrico { get; set; }
        public DbSet<agregarUsuarioTabla> agregarUsuarioTabla { get; set; }
        public DbSet<ConteoConsumoTabla> ConteoConsumoTabla { get; set; }
        public DbSet<ingresarServicio> ingresarServicio { get; set; }
        public DbSet<PrecioAlumbradoPublico> PrecioAlumbradoPublico { get; set; }
        public DbSet<PrecioKwhPorMes> PrecioKwhPorMes { get; set; }
        public DbSet<PrecioFijoComercialización> PrecioFijoComercialización { get; set; }
    }
}
